In [1]:
import sys
import numpy as np


In [2]:
np.array([1, 2, 3, 4])


array([1, 2, 3, 4])

In [3]:
a = np.array([1, 2, 3, 4])


In [4]:
b = np.array([0, .5, 1, 1.5, 2])


In [5]:
a[0], a[1]


(1, 2)

In [6]:
a[0:]


array([1, 2, 3, 4])

In [7]:
a[1:3]


array([2, 3])

In [8]:
a[1:-1]


array([2, 3])

In [9]:
a[::2]


array([1, 3])

In [10]:
b


array([0. , 0.5, 1. , 1.5, 2. ])

In [11]:
b[0], b[2], b[-1]


(0.0, 1.0, 2.0)

In [12]:
b[[0, 2, -1]]


array([0., 1., 2.])

### Array Types


In [13]:
a

array([1, 2, 3, 4])

In [14]:
a.dtype

dtype('int64')

In [15]:
b


array([0. , 0.5, 1. , 1.5, 2. ])

In [16]:
b.dtype

dtype('float64')

In [17]:
np.array([1, 2, 3, 4], dtype=np.float)


<ipython-input-17-6aadc0eb779c>:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.array([1, 2, 3, 4], dtype=np.float)


array([1., 2., 3., 4.])

In [18]:
np.array([1, 2, 3, 4], dtype=np.int8)

array([1, 2, 3, 4], dtype=int8)

In [19]:
c = np.array(['a', 'b', 'c'])

In [20]:
c.dtype

dtype('<U1')

In [21]:
d = np.array([{'a': 1}, sys])

In [22]:
d.dtype

dtype('O')

### Dimensions and shapes


In [23]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [24]:
A.shape

(2, 3)

In [25]:
A.ndim

2

In [26]:
A.size

6

In [27]:
B = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4],
        [3, 2, 1]
    ]
])



In [28]:
B

array([[[12, 11, 10],
        [ 9,  8,  7]],

       [[ 6,  5,  4],
        [ 3,  2,  1]]])

In [29]:
B.shape

(2, 2, 3)

In [30]:
B.ndim

3

In [31]:
B.size

12

In [32]:
C = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4]
    ]
])

<ipython-input-32-39b57e6bbad9>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  C = np.array([


In [33]:
C.dtype

dtype('O')

In [34]:
C.shape

(2,)

In [35]:
C.size

2

In [36]:
type(C[0])

list

### Indexing and Slicing of Matrices


In [37]:
A = np.array([
#.   0. 1. 2
    [1, 2, 3], # 0
    [4, 5, 6], # 1
    [7, 8, 9]  # 2
])

In [38]:
A[1]

array([4, 5, 6])

In [39]:
A[1][0]

4

In [40]:
A[1, 0]

4

In [41]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
A[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [43]:
A[:2, :2]

array([[1, 2],
       [4, 5]])

In [44]:
A[:2, 2:]

array([[3],
       [6]])

In [45]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
A[1] = np.array([10, 10, 10])


In [47]:
A


array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [48]:
A[2] = 99


In [49]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

#### Summary statistics


In [50]:
a = np.array([1, 2, 3, 4])

In [51]:
a.sum()

10

In [52]:
a.mean()

2.5

In [53]:
a.std()

1.118033988749895

In [54]:


a.var()

1.25

In [55]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [56]:
A.sum()

45

In [57]:
A.mean()

5.0

In [58]:


A.std()

2.581988897471611

In [59]:
A.sum(axis=0)

array([12, 15, 18])

In [60]:
A.sum(axis=1)


array([ 6, 15, 24])

In [61]:
A.mean(axis=0)

array([4., 5., 6.])

In [62]:
A.mean(axis=1)

array([2., 5., 8.])

In [63]:
A.std(axis=0)

array([2.44948974, 2.44948974, 2.44948974])

In [64]:
A.std(axis=1)

array([0.81649658, 0.81649658, 0.81649658])

### Broadcasting and Vectorized operations


In [65]:
a = np.arange(4)

In [66]:
a

array([0, 1, 2, 3])

In [67]:
a + 10

array([10, 11, 12, 13])

In [68]:
a * 10

array([ 0, 10, 20, 30])

In [69]:
a

array([0, 1, 2, 3])

In [70]:
a += 100

In [71]:
a


array([100, 101, 102, 103])

In [72]:
l = [0, 1, 2, 3]

In [73]:
[i * 10 for i in l]

[0, 10, 20, 30]

In [74]:
a = np.arange(4)

In [75]:
a

array([0, 1, 2, 3])

In [76]:
b = np.array([10, 10, 10, 10])

In [77]:
b

array([10, 10, 10, 10])

In [78]:
a + b

array([10, 11, 12, 13])

In [79]:
a * b

array([ 0, 10, 20, 30])

### Boolean arrays



In [80]:
a = np.arange(4)

In [81]:
a

array([0, 1, 2, 3])

In [82]:
a[0], a[-1]

(0, 3)

In [83]:
a[[0, -1]]

array([0, 3])

In [84]:
a[[True, False, False, True]]

array([0, 3])

In [85]:
a

array([0, 1, 2, 3])

In [86]:
a >= 2

array([False, False,  True,  True])

In [87]:
a[a >= 2]

array([2, 3])

In [88]:
a.mean()

1.5

In [89]:
a[a > a.mean()]

array([2, 3])

In [90]:
a[~(a > a.mean())]

array([0, 1])

In [91]:
a[(a == 0) | (a == 1)]

array([0, 1])

In [92]:
a[(a <= 2) & (a % 2 == 0)]

array([0, 2])

In [93]:
A = np.random.randint(100, size=(3, 3))

In [94]:
A

array([[18, 97, 67],
       [61, 82, 95],
       [57, 60, 76]])

In [95]:
A[np.array([
    [True, False, True],
    [False, True, False],
    [True, False, True]
])]

array([18, 67, 82, 57, 76])

In [96]:
A > 30

array([[False,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [97]:
A[A > 30]

array([97, 67, 61, 82, 95, 57, 60, 76])

### Linear Algebra

In [98]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [99]:
B = np.array([
    [6, 5],
    [4, 3],
    [2, 1]
])

In [100]:
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [101]:
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [102]:
B.T

array([[6, 4, 2],
       [5, 3, 1]])

In [103]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [104]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])